
services:
  client:
    build: ./client/
    command: npm run dev -- --host
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
  

  server:
    build: ./server/
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server 

